import re

def flatten_chapters(structure):
    """
    Flatten the nested TOC structure into a simple chapter list.

    Parameters
    ----------
    structure : list
        Parsed textbook structure generated by parse_toc().

    Returns
    -------
    list
        List of chapter dictionaries containing:
        - part
        - chapter_number
        - chapter_title
        - start_page
        - sections
    """

    chapters = []

    for part in structure:
        for chapter in part["chapters"]:
            chapters.append({
                "part": part["part"],
                "chapter_number": chapter["chapter_number"],
                "chapter_title": chapter["chapter_title"],
                "start_page": chapter["start_page"],
                "sections": chapter["sections"]
            })

    return chapters


def add_chapter_end_pages(chapters):
    """
    Infer chapter end pages using the next chapter start page.

    Parameters
    ----------
    chapters : list
        Flattened chapter list.

    Returns
    -------
    list
        Chapter list including:
        - end_page
    """

    chapters_with_ranges = []

    for index, chapter in enumerate(chapters):
        chapter_copy = chapter.copy()

        if index + 1 < len(chapters):
            chapter_copy["end_page"] = chapters[index + 1]["start_page"] - 1
        else:
            chapter_copy["end_page"] = None

        chapters_with_ranges.append(chapter_copy)

    return chapters_with_ranges


def apply_page_offset(chapters, offset):
    """
    Convert textbook page numbers into PDF page numbers.

    Parameters
    ----------
    chapters : list
        Chapter list containing textbook page numbers.

    offset : int
        Difference between textbook numbering and PDF indexing.

    Returns
    -------
    list
        Chapter list including:
        - pdf_start_page
        - pdf_end_page
    """

    adjusted_chapters = []

    for chapter in chapters:
        chapter_copy = chapter.copy()

        chapter_copy["pdf_start_page"] = chapter["start_page"] + offset

        if chapter["end_page"] is not None:
            chapter_copy["pdf_end_page"] = chapter["end_page"] + offset
        else:
            chapter_copy["pdf_end_page"] = None

        adjusted_chapters.append(chapter_copy)

    return adjusted_chapters


def extract_chapter_text(pages, chapter):
    """
    Extract full chapter text from PDF pages.
    """

    selected_pages = []

    pdf_start = chapter["pdf_start_page"]
    pdf_end = chapter["pdf_end_page"]

    for page in pages:
        page_number = page["page_number"]

        if pdf_end is None:
            is_inside_chapter = page_number >= pdf_start
        else:
            is_inside_chapter = (
                page_number >= pdf_start
                and page_number <= pdf_end
            )

        if is_inside_chapter:
            selected_pages.append(page["text"])

    chapter_copy = chapter.copy()
    chapter_copy["text"] = "\n".join(selected_pages)

    return chapter_copy
def extract_all_chapters_text(pages, chapters):
    """
    Extract text for all chapters.

    Parameters
    ----------
    pages : list
        PDF pages extracted from the textbook.

    chapters : list
        Chapter metadata with PDF page ranges.

    Returns
    -------
    list
        Chapters including extracted text.
    """

    return [
        extract_chapter_text(pages, chapter)
        for chapter in chapters
    ]
